
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": true,
 "error": null,
 "full-revisionid": "3b7ed6bf00fe14fcb53779fd0b72f3b494ce21e2",
 "version": "v0.0.1b+13.g3b7ed6b.dirty"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
